### PR TITLE
Matic

### PR DESCRIPTION
**Pull request by MaticSincek**
Request to merge with master

### CODE REVIEW

**Review by dejvv — APPROVED** [review]
Ok

**Review by dejvv — CHANGES_REQUESTED** [review]
- On register check if user already exists.

- Before logging user, hash password with MD5, because in database it needs to be compared as MD5 against MD5

- Same on register, hash password first and then send it to database

**Comment by MaticSincek** [comment]
Changes made as requested

**Review by dejvv — APPROVED** [review]
ok, good

**Pull request merged**
